import { useState, useEffect } from 'react'
import { timetableAPI } from '../services/api'
import Layout from './Layout'

export default function ApprovalWorkflow() {
  const [pendingTimetables, setPendingTimetables] = useState([])
  const [approvedTimetables, setApprovedTimetables] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [selectedTimetable, setSelectedTimetable] = useState(null)
  const [comments, setComments] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [actionType, setActionType] = useState('') // 'approve' or 'reject'
  const [processing, setProcessing] = useState(false)

  useEffect(() => {
    fetchTimetables()
  }, [])

  const fetchTimetables = async () => {
    try {
      setLoading(true)
      const res = await timetableAPI.getAll()
      const allTimetables = res.data || []
      
      // Separate pending (draft) and approved/rejected timetables
      const pending = allTimetables.filter(tt => tt.status === 'draft')
      const approved = allTimetables.filter(tt => 
        tt.status === 'approved' || tt.status === 'active' || tt.status === 'rejected'
      ).slice(0, 10) // Show last 10
      
      setPendingTimetables(pending.map(tt => ({
        id: tt.id,
        name: tt.name,
        generated_at: new Date(tt.generated_at).toLocaleString(),
        utilization: Math.round((tt.utilization_rate || 0) * 100),
        conflicts: tt.conflict_count || 0,
        quality_score: Math.round(tt.quality_score || 0)
      })))
      
      setApprovedTimetables(approved)
      setError('')
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to load timetables')
      console.error('Error fetching timetables:', err)
    } finally {
      setLoading(false)
    }
  }

  const handleAction = (timetable, action) => {
    setSelectedTimetable(timetable)
    setActionType(action)
    setShowModal(true)
  }

  const confirmAction = async () => {
    if (!selectedTimetable) return
    
    if (actionType === 'reject' && !comments.trim()) {
      alert('Please provide comments for rejection')
      return
    }

    setProcessing(true)
    try {
      if (actionType === 'approve') {
        await timetableAPI.approve(selectedTimetable.id, comments || 'Approved')
        alert('Timetable approved successfully!')
      } else {
        await timetableAPI.reject(selectedTimetable.id, comments)
        alert('Timetable rejected successfully!')
      }
      
      // Refresh the list
      await fetchTimetables()
      
      setShowModal(false)
      setComments('')
      setSelectedTimetable(null)
    } catch (err) {
      alert('Failed to ' + actionType + ' timetable: ' + (err.response?.data?.detail || err.message))
    } finally {
      setProcessing(false)
    }
  }

  return (
    <Layout>
      <div className="approval-workflow">
        <h2>Approval Workflow</h2>
        <p className="subtitle">Review and approve or reject generated timetables</p>

        {loading ? (
          <div className="loading-state">
            <p>Loading timetables...</p>
          </div>
        ) : error ? (
          <div className="error-state">
            <h3>Error Loading Timetables</h3>
            <p>{error}</p>
            <button onClick={fetchTimetables} className="btn-primary">
              Retry
            </button>
          </div>
        ) : pendingTimetables.length === 0 ? (
          <div className="empty-state">
            <h3>No Pending Approvals</h3>
            <p>All timetables have been reviewed</p>
          </div>
        ) : (
          <div className="approval-list">
            {pendingTimetables.map(tt => (
              <div key={tt.id} className="approval-card">
                <div className="approval-header">
                  <div>
                    <h3>{tt.name}</h3>
                    <p className="meta">
                      Generated by {tt.generated_by} on {tt.generated_at}
                    </p>
                  </div>
                  <div className="status-badge pending">Pending Review</div>
                </div>

                <div className="approval-stats">
                  <div className="stat-item">
                    <span className="stat-label">Utilization Rate</span>
                    <span className="stat-value">{tt.utilization}%</span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-label">Conflicts</span>
                    <span className={`stat-value ${tt.conflicts === 0 ? 'success' : 'warning'}`}>
                      {tt.conflicts}
                    </span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-label">Quality Score</span>
                    <span className="stat-value">{tt.quality_score}/100</span>
                  </div>
                </div>

                <div className="approval-details">
                  <h4>Key Highlights:</h4>
                  <ul>
                    <li>✓ All constraints satisfied</li>
                    <li>✓ No faculty double-booking</li>
                    <li>✓ No classroom conflicts</li>
                    <li>✓ Optimal resource utilization</li>
                  </ul>
                </div>

                <div className="approval-actions">
                  <button 
                    onClick={() => window.location.href = `/timetables?id=${tt.id}`}
                    className="btn-secondary"
                  >
                    👁️ View Details
                  </button>
                  <button 
                    onClick={() => handleAction(tt, 'reject')}
                    className="btn-danger"
                  >
                    ✗ Reject
                  </button>
                  <button 
                    onClick={() => handleAction(tt, 'approve')}
                    className="btn-success"
                  >
                    ✓ Approve
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {approvedTimetables.length > 0 && (
          <div className="approval-history">
            <h3>Recent Approval History</h3>
            <table className="history-table">
              <thead>
                <tr>
                  <th>Timetable</th>
                  <th>Status</th>
                  <th>Generated At</th>
                  <th>Utilization</th>
                  <th>Conflicts</th>
                </tr>
              </thead>
              <tbody>
                {approvedTimetables.map(tt => (
                  <tr key={tt.id}>
                    <td>{tt.name}</td>
                    <td>
                      <span className={`badge ${
                        tt.status === 'active' || tt.status === 'approved' ? 'success' : 
                        tt.status === 'rejected' ? 'danger' : 'secondary'
                      }`}>
                        {tt.status || 'draft'}
                      </span>
                    </td>
                    <td>{new Date(tt.generated_at).toLocaleString()}</td>
                    <td>{Math.round((tt.utilization_rate || 0) * 100)}%</td>
                    <td>{tt.conflict_count || 0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {showModal && (
          <div className="modal-overlay" onClick={() => setShowModal(false)}>
            <div className="modal" onClick={(e) => e.stopPropagation()}>
              <h3>
                {actionType === 'approve' ? 'Approve Timetable' : 'Reject Timetable'}
              </h3>
              <p>
                {actionType === 'approve' 
                  ? `Are you sure you want to approve "${selectedTimetable?.name}"? This will set it as the active timetable.`
                  : `Are you sure you want to reject "${selectedTimetable?.name}"?`
                }
              </p>

              {actionType === 'reject' && (
                <div className="form-group">
                  <label>Rejection Comments *</label>
                  <textarea
                    value={comments}
                    onChange={(e) => setComments(e.target.value)}
                    placeholder="Please provide reasons for rejection..."
                    rows="4"
                    required
                  />
                </div>
              )}

              <div className="modal-actions">
                <button onClick={() => setShowModal(false)} className="btn-secondary">
                  Cancel
                </button>
                <button 
                  onClick={confirmAction}
                  className={actionType === 'approve' ? 'btn-success' : 'btn-danger'}
                  disabled={(actionType === 'reject' && !comments.trim()) || processing}
                >
                  {processing ? 'Processing...' : (actionType === 'approve' ? 'Confirm Approval' : 'Confirm Rejection')}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </Layout>
  )
}
